### PR TITLE
[WAITING] remove apollo from cli

### PR DESCRIPTION
**Pull request by bergman**
- saves about 5 seconds on every call
- synchronous calls makes the code much easier to follow IMHO

### CODE REVIEW

**Comment by rouzwawi** [comment]
Cool. Out of curiosity, what made the calls take 5 seconds longer? It's surprising given that the underlying Apollo Client uses the same HTTP client.

**Comment by bergman** [comment]
Yes, the 5 second delay was probably due to some other problem and is not usually there. I still kind of like the synchronous model better than the other one for these simple cases where it's just one call.

**Comment by rouzwawi** [comment]
@bergman Can' that be achieved with just?

```
Response<ByteString> response = client.send(...).toCompletableFuture().get()
```

**Comment by bergman** [comment]
You would still have the signaller and service thing which just feels odd in a temporary client.

**Comment by rouzwawi** [comment]
The signaller was only needed because the calls where async. If the main thread blocks on the calls, the top level try-with-resource block does not have to block on `instance.waitForShutdown()`, so we can remove all the `Signaller` code.

**Comment by bergman** [comment]
You're right, will have another pass at this later.

**Pull request closed without merging**
