### PR TITLE
do not log user error InvalidExecutionException as errors

### PR DESCRIPTION
**Pull request by danielnorberg**

### CODE REVIEW

**Comment by honnix** [comment]
you are faster. add a test case covering that path?

**Comment by honnix** [comment]
`-3.33%` is it because you didn't rebase master? I just merged something to master bringing `~3%` more.

**Comment by honnix** [comment]
It feels like this logging in memory killed circleci

**Comment by danielnorberg** [comment]
Yeah =/

**Comment by danielnorberg** [comment]
Ok logback seems to work better.

**Comment by honnix** [comment]
To be honest I started questioning about how useful it is to test log levels given the complexity we need to introduce. https://github.com/spotify/styx/pull/204/files#diff-0286d095fa9d41fc6932d43e2e678cbdR215, those lines are rather hard to understand.

**Comment by danielnorberg** [comment]
@honnix yeah, I agree with that

**Comment by honnix** [comment]
Let's not verify log level in test case then. The change is still valid to push in.

**Comment by danielnorberg** [comment]
Removed the test and rebased.

**Pull request merged**
