### PR TITLE
Simplify and isolate jackson serialization types

### PR DESCRIPTION
**Pull request by rouzwawi**

### CODE REVIEW

**Comment by fabriziodemaria** [comment]
Nice! 👍

**Comment by bergman** [comment]
omg

**Comment by rouzwawi** [comment]
The main thing here is `TypeWrapperModule` which enabled `Event` and `Trigger` to directly be (de)serialized without having to use `Persistent(Event|Trigger)` in the rest of the codebase.

**Comment by bergman** [comment]
👍

**Pull request merged**
