### PR TITLE
k8s restore: retry harder

### PR DESCRIPTION
**Pull request by danielnorberg**

### CODE REVIEW

**Comment by honnix** [comment]
👍

**Comment by ulzha** [comment]
+1. Could only perhaps improve with some diagnostic logging onRetry? Trying hard and not telling the world makes the operator confused, like, what is this program doing for so long...

**Comment by danielnorberg** [comment]
@ulzha agreed

**Comment by danielnorberg** [comment]
@ulzha now pod polling failures during startup are logged, good enough?

**Pull request merged**
