### PR TITLE
[wip] Graph based scheduler

### PR DESCRIPTION
**Pull request by rouzwawi**
Opening this up for discussion. The work is not done.

The scheduler has logic that decides which workflow instances to to dequeue, taking resources into account. This PR replaces that logic with a graph flow problem (inspired by [firmament](http://firmament.io)). It is best described by an example:

graph3

The first layer after the source are all workflow instances eligible for dequeuing. Each of those are attached to a sequence of resource nodes with edges representing their limit (also reflected in the node name). There's one such path for each workflow, and they all end in the sink node.

If a resource is used by multiple workflows, the corresponding edge is aliased between the paths (dotted lines, which are not edges). Allocating flow along one of these will reduce capacity along all aliased edges.

Finally, all edges between the source and a workflow instance that have a non-zero flow will be dequeued.

Following paths from the source to the sink that have zero flow can give us a list of resources that were depleted.

## todo

- [ ] Add edge before sink for global resource limit
- [ ] Fix bug with backfills

### CODE REVIEW

**Comment by honnix** [comment]
I like graph and optimisation!

```If a resource is used by multiple workflows, the corresponding edge is aliased between the paths (dotted lines, which are not edges). Allocating flow along one of these will reduce capacity along all aliased edges.```
Didn't quite get this. Is it an extension/variation of maximum flow problem?

How many different resource types we may have? This contributes to the complexity of the network. So far it seems we have pretty simple situation and maximum flow feels a little bit overshooting (I could be wrong by not knowing all history).

```N0_source``` seems to be a "virtual" node, the capacity can be set to infinity instead of 1, is that the case?

Another thing, not so important. Have we considered using something like https://github.com/jrtom/jung which feels more bullet-proof than home brew data structure and algorithm?

**Comment by danielnorberg** [comment]
Just to clarify, would the purpose of this to be, like firmament offers, `find the policy-optimal assignment of work to cluster resources`?

I agree that the resource utilization problems we currently face would seem to benefit from an efficient bin-packing scheduler that can provide a more even data processing resource usage over time and eliminate hourly peaks etc.

However, one of the current vexing issues would seem to be that the actual resource usage of a data pipeline executed by styx is opaque to styx itself.

- Although it is possible for a user to annotate a workflow configuration with a list of consumed resources, it does not currently seem to be possible to indicate the magnitude of consumed resource. I.e., it does not seem possible to say that workflow `foo` consumes 100 cpu cores etc.

- Styx lacks facilities to enforce that workflows are annotated with some resource usage and e.g. deny/penalize workflows that claim to be "free".

- Styx is unable to use historical resource usage information to e.g. estimate resource usage of future workflow executions, etc.

- Etc...

Unless we address the above issues, would the graph scheduler actually produce high-quality scheduling descisions?

Would it make sense to start addressing these issues first?

**Comment by rouzwawi** [comment]
The main purpose of this particular PR is to give us a more flexible foundation to build on. But as you've pointed out, it won't lead to any different scheduling as it stands right now. I've tried to scope this as implementing the same logic we have right now. Perhaps with the addition of doing multi-run solves for prioritizing natural trigger instances over backfills.

>Although it is possible for a user to annotate a workflow configuration with a list of consumed resources, it does not currently seem to be possible to indicate the magnitude of consumed resource. I.e., it does not seem possible to say that workflow foo consumes 100 cpu cores etc.

This has been brought up in issue #30

On the other issues; I agree that it would be good to start addressing those. But it should not be a stopper for this PR, right?

**Comment by danielnorberg** [comment]
What is multi-run?

Yeah, these other issues might not be blockers for this PR but in practice it might mean that we have limited time to spend on the graph scheduler in the short term. And as it is seems like a non-insignificant increase in complexity, I would like to proceed with due care.

It might be beneficial to first focus on the pressing matter of preventing sharp resource usage peak induced stock-outs etc.

**Comment by rouzwawi** [comment]
multi-run: e.g. configure the flow graph for priority 1 instances, solve, dequeue, then add p2 instances, solve on remaining capacity, dequeue, etc.

**Pull request closed without merging**
