### PR TITLE
factor Middlewares class to styx-common

### PR DESCRIPTION
**Pull request by honnix**
It can be shared by both styx-api and styx-scheduler.

Also rename the middleware a bit to preare for token validation.

@danielnorberg @bergman PTAL

As a starting point. Feel free to continue or close it.

### CODE REVIEW

**Comment by danielnorberg** [comment]
Could token validation and audit logging be separate middlewares?

**Comment by honnix** [comment]
They could. Didn't have time to figure out how to pass in user account to audit logging middleware and it's not good to retrieve that twice.

**Comment by honnix** [comment]
Maybe after token validation we can annotate request object for example setting a new header.

**Comment by danielnorberg** [comment]
@honnix this seems to be the recommended way to decorate the request context: https://github.com/spotify/apollo/blob/master/apollo-api/docs/middleware.md#advanced-creating-custom-context-types

**Comment by honnix** [comment]
Doesn't look very straight forward how to pass info from out handler to inner handler though.

**Comment by danielnorberg** [comment]
Yeah, ideally it would be easy.

**Comment by honnix** [comment]
As I see this PR has been covered by #230. So close.

**Pull request closed without merging**
