### PR TITLE
styx cli: workflow show

### PR DESCRIPTION
**Pull request by danielnorberg**
Add a `workflow show <component> <workflow>` command.

```
$ styx workflow show dano-test-pipeline dano-test
Component: dano-test-pipeline
 Workflow: dano-test
  Enabled: false
 Schedule: DAYS
   Commit: 79b49cdd161d3f17b43f005be22ead4095ca35c8
    Image: registry.spotify.net/spotify/dano-test-pipeline:1490015757-d811bbe@sha256:c666cbfb44ac1debc3bb709a0268d19e3cd4e45a4d204dcbb4c3455b70c7dff7
     Args: [bash, -c, echo hello digest world {}]
```

The output of the command is a `Workflow` with some fields from `WorkflowState` added / merged. Notably the `WorkflowState` takes precedence for the `Image` field value.

### CODE REVIEW

**Comment by danielnorberg** [comment]
@honnix PTAL

**Comment by danielnorberg** [comment]
@rouzwawi Would it make sense to use the workflow id "key" in these kinds of cli commands?

E.g. 

```
$ styx workflow show dano-test-pipeline#dano-test
 Workflow: dano-test-pipeline#dano-test
  Enabled: false
 Schedule: DAYS
   Commit: 79b49cdd161d3f17b43f005be22ead4095ca35c8
    Image: registry.spotify.net/spotify/dano-test-pipeline:1490015757-d811bbe@sha256:c666cbfb44ac1debc3bb709a0268d19e3cd4e45a4d204dcbb4c3455b70c7dff7
     Args: [bash, -c, echo hello digest world {}]
```

**Comment by honnix** [comment]
👍 

Just to mention this will bring some rework to #114.

Regarding that question, to me it feels better not to expose the internal workflow key.

**Comment by danielnorberg** [comment]
@honnix right, wasn't sure if it the purpose of the key was only to be used as internal identifier. It seems useful to be able to refer to workflows and instances using a single id string instead of having to use a list of strings. 

E.g.

`dano-test-pipeline#dano-test` vs `dano-test-pipeline dano-test`
and
`dano-test-pipeline#dano-test@2017-01-02` vs `dano-test-pipeline dano-test 2017-01-02`

**Pull request merged**
