### PR TITLE
use 2 series

### PR DESCRIPTION
**Pull request by honnix**
@fabriziodemaria @danielnorberg Let's take it as a separated PR.

### CODE REVIEW

**Comment by danielnorberg** [comment]
okhttp 2 is obsolete tho: https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-300-rc1

> This release obsoletes OkHttp 2.x, and all code that uses OkHttp's com.squareup.okhttp package should upgrade to the okhttp3 package. Libraries that depend on OkHttp should upgrade quickly to prevent applications from being stuck on the old version.

**Comment by honnix** [comment]
Yeah unfortunately. But we probably want to go with Apollo.

**Comment by danielnorberg** [comment]
We should submit a PR to apollo to upgrade to okhttp3 as well I guess.

**Comment by honnix** [comment]
@danielnorberg feel free to merge this if it's OK.

**Comment by honnix** [comment]
https://github.com/spotify/apollo/pull/220 :D

**Comment by danielnorberg** [comment]
@honnix thanks =)

**Comment by honnix** [comment]
OK to merge for now? This jar is now included for nothing.

**Comment by danielnorberg** [comment]
But then we end up with an explicit dependency on the obsolete okhttp...

**Comment by honnix** [comment]
That's true. I think there is little chance that Apollo 1.x will upgrade to okhttp3 https://github.com/spotify/apollo/pull/224

If we want to use okhttp3 explicitly here, let's fix the imported packages.

**Comment by honnix** [comment]
https://github.com/spotify/styx/pull/316

**Comment by danielnorberg** [comment]
I interpreted https://github.com/spotify/apollo/pull/220#issuecomment-338992850 as upgrading to okhttp3 being positively considered for Apollo 1.x as well

**Comment by honnix** [comment]
in favor of #316

**Pull request closed without merging**
