### PR TITLE
restore apollo client tests

### PR DESCRIPTION
**Pull request by danielnorberg**
Put `StyxApolloClientTest.java` back in the correct location so maven and intellij picks it up.

#316

### CODE REVIEW

**Comment by danielnorberg** [comment]
@honnix PTAL

**Comment by danielnorberg** [comment]
Not sure how codecov thinks this PR decreases coverage. Maybe it's drunk.

From circle-ci building [this PR](https://circleci.com/gh/spotify/styx/2219):

```
Running com.spotify.styx.client.StyxApolloClientTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.139 sec - in com.spotify.styx.client.StyxApolloClientTest
```

Compared to building [master](https://circleci.com/gh/spotify/styx/2213):
```
... no mention of StyxApolloClientTest ...
```

**Comment by honnix** [comment]
How did that happen in #316? :(

+1

**Comment by honnix** [comment]
https://codecov.io/gh/spotify/styx/compare/4fb9b50b657c13117fe25c745b0ea44b96acee2d...1e6a0f582e078c38411ff3472296fddd14387ebd/changes

**Comment by danielnorberg** [comment]
@honnix yeah, restoring this test means that those files start showing up in the coverage report at all, and with low coverage, which causes codecov to fail the review =(

**Pull request merged**
