### PR TITLE
remove duplicated scheme

### PR DESCRIPTION
**Pull request by honnix**
# Hey, I just made a Pull Request!

## Checklist for PR author(s)

- [ ] Changes are covered by unit test
- [ ] All tests pass
- [ ] Code coverage check passes
- [ ] Error handling is tested
- [ ] Errors are handled at the appropriate layer
- [ ] Errors that cannot be handled where they occur are propagated
- [ ] (optional) Changes are covered by system test
- [ ] Relevant documentation updated
- [ ] This PR has NO breaking change to public API
- [ ] This PR has breaking change to public API and it is documented

## Checklist for PR reviewer(s)

- [ ] This PR has been incorporated in release note for the coming version
- [ ] Risky changes introduced by this PR have been all considered

### CODE REVIEW

**Comment by honnix** [comment]
@bergman PTAL

**Comment by honnix** [comment]
@bergman PTAL

**Comment by Zatine** [comment]
👍

**Comment by bergman** [comment]
👍 (the wording `..._HOST` should make it clear that the protocol is not expected, compared to something like `..._URI`)

**Comment by danielnorberg** [comment]
@bergman yeah, `DOCKER_HOST` taught me to not assume that 😅

**Pull request merged**
