### PR TITLE
according to issue #217

### PR DESCRIPTION
**Pull request by honnix**
those logs shall be debug instead of info.

@fabriziodemaria PTAL, we have enabled debug logging, so...

### CODE REVIEW

**Comment by honnix** [comment]
Would this change break some of our metrics? Because debug logs will not be shipped to stackdriver.

**Comment by fabriziodemaria** [comment]
I'd remove `transitionLogger` completely, since we log already from here:
https://github.com/spotify/styx/blob/1ebd23a9ff4ff17234eb97ef79f54efa6c968d28/styx-common/src/main/java/com/spotify/styx/util/ReplayEvents.java#L106

Hopefully this will also enable us to move `OutputHandler` class out from `styx-common` module.

**Comment by honnix** [comment]
interesting `transitionLogger` is not only for replaying, but happen to be in `ReplayEvents`.

**Comment by honnix** [comment]
Let's first decouple it from `ReplayEvents`. Moving `OutputHandler` requires quite some change.

**Comment by honnix** [comment]
@fabriziodemaria Please take another look.

**Comment by honnix** [comment]
@fabriziodemaria Would this break any Stackdriver metrics?

**Comment by honnix** [comment]
`info` might still be needed. close for now, but factoring out `transitionLogger` is better to have.

**Pull request closed without merging**
