### PR TITLE
fix api doc

### PR DESCRIPTION
**Pull request by honnix**
# Hey, I just made a Pull Request!

## Description

This is event is missing `parameters`.

## Motivation and Context

Fix api doc.

## Checklist for PR author(s)

- [ ] Changes are covered by unit test
- [ ] All tests pass
- [ ] Code coverage check passes
- [ ] Error handling is tested
- [ ] Errors are handled at the appropriate layer
- [ ] Errors that cannot be handled where they occur are propagated
- [ ] (optional) Changes are covered by system test
- [x] Relevant documentation updated
- [x] This PR has NO breaking change to public API
- [ ] This PR has breaking change to public API and it is documented

## Checklist for PR reviewer(s)

- [ ] This PR has been incorporated in release note for the coming version
- [ ] Risky changes introduced by this PR have been all considered

### CODE REVIEW

**Comment by honnix** [comment]
PTAL @danielnorberg

**Comment by honnix** [comment]
PTAL @danielnorberg

**Comment by danielnorberg** [comment]
👍

**Comment by honnix** [comment]
`WorkflowResourceTest.shouldReturnBadRequestWhenMalformedStatePayloadIsSent[V3] » IllegalState`

flaky test?

**Pull request merged**
