### PR TITLE
Return InstancesReadResult instead of Tuple2<>

### PR DESCRIPTION
**Pull request by danielnorberg**
# Hey, I just made a Pull Request!

## Description
Return `InstancesReadResult` instead of `Tuple2<>` from `readActiveStatesPartial`.

## Motivation and Context
Make the api a little more maintainable and introspectible.

## Checklist for PR author(s)

- [ ] Changes are covered by unit test
- [ ] All tests pass
- [ ] Code coverage check passes
- [ ] Error handling is tested
- [ ] Errors are handled at the appropriate layer
- [ ] Errors that cannot be handled where they occur are propagated
- [ ] (optional) Changes are covered by system test
- [ ] Relevant documentation updated
- [ ] This PR has NO breaking change to public API
- [ ] This PR has breaking change to public API and it is documented

## Checklist for PR reviewer(s)

- [ ] This PR has been incorporated in release note for the coming version
- [ ] Risky changes introduced by this PR have been all considered

### CODE REVIEW

**Comment by honnix** [comment]
wip?

**Comment by danielnorberg** [comment]
Yeah, I'm not even sure if we should keep this partial read code or go back to assuming that datastore is either completely up or completely down.

**Comment by honnix** [comment]
Wait for postmortem where we will make decision whether to keep the hotfix.

**Comment by danielnorberg** [comment]
I think we can close this one.

**Pull request closed without merging**
