### PR TITLE
by default do not check counter

### PR DESCRIPTION
**Pull request by honnix**
I tend to make default behaviour not to check counter. Those places where we require counter check should call the other method explicitly.
@fabriziodemaria PTAL and let's discuss it.

### CODE REVIEW

**Comment by honnix** [comment]
Or we fix it like #431 in commit https://github.com/spotify/styx/pull/431/commits/e95341a84095446190651e2fbb0629193d0426b6

**Comment by danielnorberg** [comment]
I think this change still makes sense. Ignoring e.g. an incoming `halt` due to concurrent event processing seems undesirable, which seems like it might happen as things are right now.

**Comment by honnix** [comment]
There could be cases that it is so slow that a termination event for previous execution gets handled for current execution. But this is rather remote case.

**Comment by honnix** [comment]
@danielnorberg I tend to get this merged and shipped.

**Comment by danielnorberg** [comment]
I think we should handle case of termination events from the previous execution by filtering on the current execution id _in the state machine transition transaction_. E.g. instead of just injecting an event into the QSM, inject a lambda that gets executed in the transaction and that can abort if the pod event is stale.

**Comment by danielnorberg** [comment]
👍

**Pull request merged**
