### PR TITLE
do not return Optional.empty() as null

### LINKED ISSUE #117: enabled and next_natural_trigger values being null
When patching at component level, `enabled` and `next_natural_trigger` in response should not be `null`.

### PR DESCRIPTION
**Pull request by honnix**
fix #117

### CODE REVIEW

**Comment by honnix** [comment]
This is a more general problem maybe. For many cases we return `null` in json, should we not include it at all? Semantically they are very similar, but visually feels strange.

**Comment by rouzwawi** [comment]
I think it's more informative to return `null` than omitting the field.

Also, the `WorkflowState` type has a dual role. It's used both for parsing PATCH requests (where everything is optional) and for returning the GET payload.

**Comment by honnix** [comment]
I don't have strong opinions as long as it is consistent throughout the system.

**Comment by honnix** [comment]
close #117

**Pull request closed without merging**
