### PR TITLE
fix pod creation / deletion race

### PR DESCRIPTION
**Pull request by danielnorberg**
Looks like this behavior was introduced in https://github.com/spotify/styx/pull/282

### CODE REVIEW

**Comment by danielnorberg** [comment]
@honnix wdyt about this, is it a real race? Afaict this behavior has not changed recently, but I noticed it now.

**Comment by danielnorberg** [comment]
Looking at the event trace from a successfully executed pod, there's a window of time where it is still `Pending` with an empty `containerStatuses` before the container creation process has started.

**Comment by honnix** [comment]
I think the old behavior was if not container status don’t do anything.

**Comment by honnix** [comment]
👍

**Pull request merged**
