### PR TITLE
k8s: keep reference to watcher

### PR DESCRIPTION
**Pull request by bergman**
@honnix i found this old branch, do you think it's still needed?

### CODE REVIEW

**Comment by bergman** [comment]
Doesn't it solve the problem of not having the reference to the new watcher saved somewhere? The `this` is needed to point to the instance of `KubernetesDockerRunner`.

**Comment by honnix** [comment]
That problem it does solve. But still we get watcher disconnected and retries occasionally. However it does recover after a while.

👍

**Comment by danielnorberg** [comment]
👍

**Comment by bergman** [comment]
Closing this since honnix already fixed it earlier.

**Pull request closed without merging**
