### PR TITLE
register active states while starting up

### PR DESCRIPTION
**Pull request by honnix**
@fabriziodemaria PTAL

### CODE REVIEW

**Comment by fabriziodemaria** [comment]
Is there any possible race condition due to the fact that we call `setupMetrics` after `startScheduleSources`? We can get a workflow changed via ScheduleSource while registering all the workflows in the cache.

Also I think in `workflowChanged` method, the registering code should happen after the `isGreaterOrEqualApiVersion` check.

**Comment by honnix** [comment]
Race condition is fine I think. It is a ConcurrentMap and `.all()` returns of copy. The metric registration is also ConcurrentMap.

Yeah, that should be moved after version check.

**Comment by fabriziodemaria** [comment]
👍

**Comment by danielnorberg** [comment]
👍

**Pull request merged**
