### PR TITLE
OkHttp client in cli

### PR DESCRIPTION
**Pull request by bergman**
pros:
- no service, instance and all that

cons:
- apollo client not dog fooded

### CODE REVIEW

**Comment by honnix** [comment]
Wait for #328 and #326 ?

**Comment by bergman** [comment]
sure, this can wait

**Comment by danielnorberg** [comment]
Does this make the cli faster?

Tests would be great.

**Comment by bergman** [comment]
I don't know about any improvements in speed but the starting-a-service-to-make-a-request dance is embarrassing.

**Comment by danielnorberg** [comment]
Yeah, the Apollo scaffolding does seem a bit excessive and although we do get some configuration for free I'm not sure we need it.

However, would be good to not have both the `StyxOkHttpClient` and `StyxApolloClient` duplicate implementations of `StyxClient`. How about keeping `StyxApolloClient` and passing it a `OkHttpClient` in a apollo `Client` [wrapper](https://github.com/spotify/apollo/blob/master/modules/okhttp-client/src/main/java/com/spotify/apollo/http/client/HttpClient.java)?

**Comment by bergman** [comment]
Hmm, yeah, thanks for the pointer to the apollo wrapper thing, will check out!

**Comment by bergman** [comment]
That apollo http client wrapper is private 😢

**Comment by danielnorberg** [comment]
I thought it would be a trivial amount of code to replicate that wrapper in styx, but alas, it seems to not be so 😫  

I'd be happy with not using the apollo client at all. I.e., remove `StyxApolloClient` etc. It would be nice if we do that in a way that keeps git history. I.e., rename `StyxApolloClient` to `StyxOkHttpClient` and make surgical changes to replace the apollo client with the okhttp client in a single commit 🤓 

How about switching to grpc at some point? 😄

**Comment by bergman** [comment]
The apollo client seems useful to any apollo services that want to integrate with styx but I guess it's easier to get a http client from an apollo client than the other way around… I'll take a stab at going apollo->http and if that's easy enough we could go http only for the client.

grpc would be amazing! Any ideas on how hard it would be for others to integrate our client if we go that route? Since we added auth, it's pretty hard to curl anyway… but any web/javascript integrations would still need http i guess.

**Comment by danielnorberg** [comment]
What would be the impact to apollo services if the styx client doesn't use the apollo client?

Afaik the apollo client is typically not used when talking to external services using client libraries. E.g. google pubsub, gcs, dataflow, etc. If that's fine for those services, maybe it would be fine for styx as well?

**Comment by danielnorberg** [comment]
I guess grpc would complicate things for talking to styx directly from a browser. Are we planning to do that? Maybe e.g. the [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) can be used to handle that when/if necessary.

**Comment by bergman** [comment]
Closing as stale.

**Pull request closed without merging**
